#!/usr/bin/env python3
"""
apply_selections.py — Parse PR body checkboxes and delete unchecked drafts.

Called by .github/workflows/publish-drafts.yml on PR merge.
Reads the PR body (stdin or --body <file>), finds checkbox lines with draft
filenames, and deletes any unchecked drafts from _drafts/.

Checkbox format (generated by triage prompt):
  - [x] **[CRITICAL]** Title Here — `2026-04-08-slug.md`
  - [ ] **[MEDIUM]** Skipped Title — `2026-04-08-other-slug.md`
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DRAFTS_DIR = ROOT / "_drafts"

# Matches: - [ ] or - [x] ... — `filename.md`
CHECKBOX_RE = re.compile(
    r"^- \[([ xX])\] .+?[—–-]\s*`([^`]+\.md)`",
    re.MULTILINE,
)


def apply_selections(body: str, dry_run: bool = False) -> int:
    matches = list(CHECKBOX_RE.finditer(body))
    if not matches:
        print("apply_selections: no checkboxes found in PR body, skipping", file=sys.stderr)
        return 0

    deleted = 0
    kept = 0

    for m in matches:
        checked = m.group(1).lower() == "x"
        filename = m.group(2).strip()
        draft = DRAFTS_DIR / filename

        if checked:
            kept += 1
            continue

        # Unchecked — delete the draft
        if draft.exists():
            print(f"  [DEL]  {filename} (unchecked)", file=sys.stderr)
            if not dry_run:
                draft.unlink()
            deleted += 1
        else:
            print(f"  [MISS] {filename} (not found in _drafts/)", file=sys.stderr)

    label = " (dry run)" if dry_run else ""
    print(f"\napply_selections: {kept} kept, {deleted} deleted{label}", file=sys.stderr)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Delete unchecked drafts based on PR body checkboxes")
    ap.add_argument("--body", type=str, help="Path to file containing PR body (default: stdin)")
    ap.add_argument("--dry-run", action="store_true", help="Report without deleting")
    args = ap.parse_args()

    if args.body:
        body = Path(args.body).read_text()
    else:
        body = sys.stdin.read()

    return apply_selections(body, dry_run=args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
